CREATE TABLE IF NOT EXISTS Ganres (
id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artists (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS Albums (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
release_year integer NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistsGanres (
artist_id INTEGER REFERENCES Artists(id),
ganre_id INTEGER REFERENCES Ganres(id),
CONSTRAINT ag PRIMARY KEY(artist_id,ganre_id) 
);


CREATE TABLE IF NOT EXISTS ArtistsAlbums (
artist_id INTEGER REFERENCES Artists(id),
album_id INTEGER REFERENCES Albums(id),
CONSTRAINT aa PRIMARY KEY(artist_id,album_id) 
);


CREATE TABLE IF NOT EXISTS Tracks (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
duration TIME NOT NULL,
album_id INTEGER REFERENCES Albums(id)
);


CREATE TABLE IF NOT EXISTS COLLECTIONS (
track_id INTEGER REFERENCES Tracks(id),
album_id INTEGER REFERENCES Albums(id),
name VARCHAR(100) NOT NULL,
release_year INTEGER NOT NULL,
CONSTRAINT ta PRIMARY KEY(track_id,album_id)
);


ALTER TABLE collections DROP CONSTRAINT ta;


